### PR TITLE
Change the directory references to reflect the new name, update variables and all other 'hyperterm' references

### PR DESCRIPTION
**Pull request by Net-Geek**
#15 I also included changing the references to this repository and NPMJS package info. I'm assuming you'll want to update the name of this repo and deprecate your old published package in favor of the new 'Hyper' name.

### CODE REVIEW

**Comment by dfrankland** [comment]
Nice! I will try to test and merge ASAP.

**Comment by Net-Geek** [comment]
Please do test. I am actually having issues with nodegit and could not test myself. But, the changes seem straightforward enough.

**Comment by jakelazaroff** [comment]
Ping? The library doesn't work without this.

**Comment by dfrankland** [comment]
@jakelazaroff my apologies, I have been a little busy. I'll try my best to get this out soon, I appreciate your patience.

**Comment by dfrankland** [comment]
Tested, and everything looks good. There a few other updates that need to happen before I do the next `npm` release though. `nodegit` isn't playing nice for example.

**Comment by jakelazaroff** [comment]
No worries! Thanks for making it happen 😄

**Pull request merged**
