### PR TITLE
Fix electron.app undefined

### LINKED ISSUE #41: Does not work with Hyper v3 Stable
Extension does not work with the latest stable release of Hyper v3. It is possibly due to the change in the config file location from `%UserProfile%\.hyper.js` to `%AppData%\Hyper\.hyper.js`. Could you update the extension to reflect this change?

### PR DESCRIPTION
**Pull request by NVFP4**
- Add "pretty" command to run prettier

Should fix #41 #43 & #45

### CODE REVIEW

**Review by dbhagen — APPROVED** [review]
These changes look go to me, I recommend merging these in.

**Comment by NVFP4** [comment]
"Only those with write access to this repository can merge pull requests."
¯\\_(ツ)_/¯

**Comment by dfrankland** [comment]
🤷‍♂

**Comment by dfrankland** [comment]
Released as 3.0.3

**Pull request merged**
